apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |
      [
          {
              "apiVersion": "ocs.openshift.io/v1alpha1",
              "kind": "StorageCluster",
              "metadata": {
                  "name": "example-storagecluster",
                  "namespace": "openshift-storage"
              },
              "spec": {
                  "manageNodes": false
              }
          },
          {
              "apiVersion": "ceph.rook.io/v1",
              "kind": "CephCluster",
              "metadata": {
                  "name": "my-rook-ceph",
                  "namespace": "my-rook-ceph"
              },
              "spec": {
                  "cephVersion": {
                      "image": "ceph/ceph:v14.2.1-20190430"
                  },
                  "dataDirHostPath": "/var/lib/rook",
                  "mon": {
                      "count": 3
                  },
                  "dashboard": {
                      "enabled": true
                  },
                  "network": {
                      "hostNetwork": false
                  },
                  "rbdMirroring": {
                      "workers": 0
                  },
                  "storage": {
                      "useAllNodes": true,
                      "useAllDevices": true
                  }
              }
          },
          {
              "apiVersion": "ceph.rook.io/v1",
              "kind": "CephBlockPool",
              "metadata": {
                  "name": "replicapool",
                  "namespace": "my-rook-ceph"
              },
              "spec": {
                  "failureDomain": "host",
                  "replicated": {
                      "size": 3
                  },
                  "annotations": null
              }
          },
          {
              "apiVersion": "ceph.rook.io/v1",
              "kind": "CephObjectStore",
              "metadata": {
                  "name": "my-store",
                  "namespace": "my-rook-ceph"
              },
              "spec": {
                  "metadataPool": {
                      "failureDomain": "host",
                      "replicated": {
                          "size": 3
                      }
                  },
                  "dataPool": {
                      "failureDomain": "host",
                      "replicated": {
                          "size": 3
                      }
                  },
                  "gateway": {
                      "type": "s3",
                      "sslCertificateRef": null,
                      "port": 8080,
                      "securePort": null,
                      "instances": 1,
                      "allNodes": false,
                      "placement": null,
                      "annotations": null,
                      "resources": null
                  }
              }
          },
          {
              "apiVersion": "ceph.rook.io/v1",
              "kind": "CephObjectStoreUser",
              "metadata": {
                  "name": "my-user",
                  "namespace": "my-rook-ceph"
              },
              "spec": {
                  "store": "my-store",
                  "displayName": "my display name"
              }
          }
      ]
    capabilities: Full Lifecycle
    categories: Storage
  name: ocs-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: StorageCluster
      name: storageclusters.ocs.openshift.io
      version: v1alpha1
      displayName: Storage Cluster
      description: Storage Cluster represents a Rook Ceph storage cluster including all the storage and compute resources required.
    - description: Represents a Ceph cluster.
      displayName: Ceph Cluster
      kind: CephCluster
      name: cephclusters.ceph.rook.io
      version: v1
    - description: Represents a Ceph Block Pool.
      displayName: Ceph Block Pool
      kind: CephBlockPool
      name: cephblockpools.ceph.rook.io
      version: v1
    - description: Represents a Ceph Object Store.
      displayName: Ceph Object Store
      kind: CephObjectStore
      name: cephobjectstores.ceph.rook.io
      version: v1
    - description: Represents a Ceph Object Store User.
      displayName: Ceph Object Store User
      kind: CephObjectStoreUser
      name: cephobjectstoreusers.ceph.rook.io
      version: v1
  description: |
    Red Hat Openshift Container Storage (OCS) provides hyperconverged storage for applications within an Openshift cluster.

    The OCS operator is the primary operator for Red Hat OpenShift Container Storage (OCS). It serves to facilitate the other operators in OCS by performing administrative tasks outside their scope as well as watching and configuring their CustomResources.
  displayName: Openshift Container Storage Operator
  install:
    spec:
      deployments:
      - name: ocs-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ocs-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ocs-operator
            spec:
              containers:
              - command:
                - ocs-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ocs-operator
                image: quay.io/openshift/ocs-operator:v0.0.1
                imagePullPolicy: Always
                name: ocs-operator
                ports:
                - containerPort: 60000
                  name: metrics
                readinessProbe:
                  exec:
                    command:
                    - stat
                    - /tmp/operator-sdk-ready
                  failureThreshold: 1
                  initialDelaySeconds: 4
                  periodSeconds: 10
                resources: {}
              serviceAccountName: ocs-operator
      - name: rook-ceph-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: rook-ceph-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: rook-ceph-operator
            spec:
              containers:
              - args:
                - ceph
                - operator
                env:
                - name: ROOK_CURRENT_NAMESPACE_ONLY
                  value: "true"
                - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
                  value: "false"
                - name: ROOK_LOG_LEVEL
                  value: INFO
                - name: ROOK_CEPH_STATUS_CHECK_INTERVAL
                  value: 60s
                - name: ROOK_MON_HEALTHCHECK_INTERVAL
                  value: 45s
                - name: ROOK_MON_OUT_TIMEOUT
                  value: 600s
                - name: ROOK_DISCOVER_DEVICES_INTERVAL
                  value: 60m
                - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
                  value: "false"
                - name: ROOK_ENABLE_SELINUX_RELABELING
                  value: "true"
                - name: ROOK_ENABLE_FSGROUP
                  value: "true"
                - name: ROOK_DISABLE_DEVICE_HOTPLUG
                  value: "false"
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: rook/ceph:v1.0.1
                name: rook-ceph-operator
                resources: {}
                volumeMounts:
                - mountPath: /var/lib/rook
                  name: rook-config
                - mountPath: /etc/ceph
                  name: default-config-dir
              serviceAccountName: rook-ceph-system
              volumes:
              - emptyDir: {}
                name: rook-config
              - emptyDir: {}
                name: default-config-dir
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - ocs.openshift.io
          resources:
          - '*'
          - storageclusters
          verbs:
          - '*'
        serviceAccountName: ocs-operator
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - services
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - statefulsets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        serviceAccountName: rook-ceph-system
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        serviceAccountName: rook-ceph-osd
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - ceph.rook.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: rook-ceph-mgr
      clusterPermissions:
      - rules: []
        serviceAccountName: rook-ceph-cluster-mgmt
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/log
          - services
          - configmaps
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        serviceAccountName: rook-ceph-system
      - rules: []
        serviceAccountName: rook-ceph-global
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - nodes
          - nodes/proxy
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          - persistentvolumes
          - persistentvolumeclaims
          - endpoints
          verbs:
          - get
          - list
          - watch
          - patch
          - create
          - update
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - delete
        - apiGroups:
          - ceph.rook.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rook.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: rook-ceph-system
      - rules: []
        serviceAccountName: rook-ceph-mgr-cluster
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - nodes
          - nodes/proxy
          verbs:
          - get
          - list
          - watch
        serviceAccountName: rook-ceph-mgr
      - rules: []
        serviceAccountName: rook-ceph-mgr-system
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        serviceAccountName: rook-ceph-mgr
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  maturity: alpha
  version: 0.0.1
  minKubeVersion: v1.13.0
  provider:
    name: Red Hat
  maintainers:
  - name: Jose Riviera
    email: jarrpa@redhat.com
  - name: Kaushal M
    email: kaushal@redhat.com
  links:
  - name: Source Code
    url: https://github.com/openshift/ocs-operator
  keywords:
  - storage
  - rook
  - ceph
  - block storage
  - shared filesystem
